### ISSUE TITLE
PendingGroup doesn't clean up that causes proxy can't start bootstraping or grouping

### ISSUE THREAD

**Issue by ericnien** [DOSNetwork/eth-contracts#15]
Version : Beta 1.0
In the following case, proxy can't start bootstraping or grouping.
Currently cleanUpOldestExpiredPendingGroup is in signalDissolve that only check the length of expiredWorkingGroupIds.
If there is no expiredWorkingGroup then it would not clean up expired pending group.
|WorkingGroupSize :0
|ExpiredGroupSize :0
|PendingGroupSize :3
|PendingNodeSize  :138

Suggestion:
CleanupExpiredPendingGroup needs a separate guardian function .

**Comment by testrain** [comment]
Fixed in 1bc08ab95abf9abe62212cbaaef237e5215ed5e3
