### ISSUE TITLE
Multiple security issues [crytic.io]

### ISSUE THREAD

**Issue by montyly** [DOSNetwork/eth-contracts#27]
Hi 

I am a security researcher at [Trail of Bits](https://www.trailofbits.com/). I ran [crytic.io](https://crytic.io/) on your codebase, and some of the findings might be of interest to you. 

Crytic is a GitHub application that provides continuous assurance for smart contracts. It runs a set of bugs and optimizations detectors on every commit and allows evaluating custom properties.

# Issue 1: ABI encodePacked Collision
## Description
DOSProxy uses the encodePacked Solidity function with two consecutive strings (dataSource and selector):
https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSProxy.sol#L484-L485

This schema is vulnerable to a collision, where two calls to query with different dataSource and selector can result in the same queryId (see the [Solidity documentation](https://solidity.readthedocs.io/en/latest/abi-spec.html#non-standard-packed-mode)).

## Recommendation
Do not use more than one dynamic type in encodePacked. One solution here might be to first hash with keccak256 both dataSource and selector.

## Crytic original finding 
![image](https://user-images.githubusercontent.com/13798342/78115896-c100cb00-7403-11ea-9cff-d071c1eb08b8.png)

# Issue 2: Deletion on mappings containing structure
## Description
[Staking.Delegation](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L68-L79), [Staking.Node](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L43-L61), and [DOSProxy.PendingGroup](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSProxy.sol#L66-L72) are structures containing mappings that are deleted ([Staking.sol#L517](https://github.com/DOSNetwork/eth-contracts/blob/master/contracts/Staking.sol#L517), [Staking.sol#L463](https://github.com/DOSNetwork/eth-contracts/blob/master/contracts/Staking.sol#L463), [Staking.sol#L300](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L300), [DOSProxy.sol#L1010](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSProxy.sol#L1010), [DOSProxy.sol#L668](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSProxy.sol#L609)). Due to the way Solidity represents mapping, deleting the structure will not delete the mapping items. As a result, the associated mapping items will be available after the structure deletion and might lead to unexpected behaviors. 

# Recommendation
A solution is to add a new field to the structure: `is_alive`, which would be set to True when the structure is created. Any access to the structure's mappings will then need to check if this field is still set to True.

# Crytic original finding

![image](https://user-images.githubusercontent.com/13798342/78116495-ab3fd580-7404-11ea-84bf-053c67f3c101.png)

# Issue 3: Unused return values
# Description
The return value of many external calls is not checked, including for ERC20.transferFrom. This behavior is error-prone. 

In the case of transferFrom, if the Staking contract were to be used with an ERC20 token that does not revert in case of failure, but returns false, an attacker will be able, for example, to create new nodes without [staking tokens](https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L174).

The calls with a missing check are:
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L174
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L176
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L233
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L245
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L278
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L505
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/Staking.sol#L524
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSPayment.sol#L171
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSPayment.sol#L219
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSPayment.sol#L230
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSPayment.sol#L257
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSPayment.sol#L181
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSOnChainSDK.sol#L61
- https://github.com/DOSNetwork/eth-contracts/blob/1649d133306d6e972c42d096c868bbbc2a8981ff/contracts/DOSOnChainSDK.sol#L50

## Recommendation
Check for the return value of all the calls listed above.

Let me know if you have any questions regarding these findings or Crytic. 
You can also reach ask questions on [our slack](https://empireslacking.herokuapp.com/) (#crytic).

**Comment by testrain** [comment]
Hi @montyly , thanks for pointing out potential problems!

> 1. The encodePacked collision problem

It has been fixed with `abi.encode()`. Thanks for reaching out!

> 2. Deleting struct with inside mappping:

I'm aware that deleting a struct won't reset the mapping inside the struct (but other fields will be reset to 0). So the struct (like Node, Delegation) comes with primary keys (like ownerAddr, delegatedNode, etc.), primary keys are checked first and ensured valid before further operation with the struct. In case of deleting a struct, although mappings inside the struct are left uncleared, but those primary keys will always be reset. **That means, those primary keys have acted like `is_alive` field and we're fine.**

> 3. transferFrom / transfer without checking return values:

You're right that external call should be used with care in smart contract, but here the check of return value of transferFrom / transfer is not necessary, as **for our token contract the return value of transferFrom / transfer will always be true**, any abnormal condition (overflow, transfer failure, etc.) has already been check and will be reverted inside transferFrom(). 

Thank you again for the help, and we're glad to communicate more if needed.

Cheers!

**Comment by montyly** [comment]
Great, thanks for these details.

As the `abi.encode` issue is fixed and the others are acknowledged, I am closing this issue. 

As you might have noticed, [crytic.io](https://crytic.io/) is currently free for three months. Don't hesitate to let me know if you want to try it or if you have any questions.
